{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.3.aar",
          "url": "paid-drama-sdk-1.0.3.aar",
          "size": 784322,
          "sha512": "e3c8bab107549bd7b05f23f35c43426a67be0d9a85753f1ad03ccd5ed0deb1e706562ae3f39031e65a16f2aab5dcb50608b8d5bb024d620eafbe24b53cabe620",
          "sha256": "5a436ba7c926cb14b48e0c2e27955866cb6018d9d710b2e9cf8b4414a72e10ac",
          "sha1": "e9f0a2db74cbdf1fb02b87f924c0c01ae4a0e278",
          "md5": "73418235194924e49a008f766873d737"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.3.aar",
          "url": "paid-drama-sdk-1.0.3.aar",
          "size": 784322,
          "sha512": "e3c8bab107549bd7b05f23f35c43426a67be0d9a85753f1ad03ccd5ed0deb1e706562ae3f39031e65a16f2aab5dcb50608b8d5bb024d620eafbe24b53cabe620",
          "sha256": "5a436ba7c926cb14b48e0c2e27955866cb6018d9d710b2e9cf8b4414a72e10ac",
          "sha1": "e9f0a2db74cbdf1fb02b87f924c0c01ae4a0e278",
          "md5": "73418235194924e49a008f766873d737"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.3-sources.jar",
          "url": "paid-drama-sdk-1.0.3-sources.jar",
          "size": 95695,
          "sha512": "163c1c319cfa9288690f932d456f40350c9ac959b704301e6858752b601b6c51129c9349859fd2dc4dd72057b70572149a3ce647a45ff618670843a1f327528d",
          "sha256": "b2f12820bc91aba75f91216ecb9e727f322dbf9228de9dae86ecb2669f126623",
          "sha1": "07f74e5b70141698f929222159bdff89f25b2268",
          "md5": "b06dbe3979415116fdc260d1a8366596"
        }
      ]
    }
  ]
}
