{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.3.aar",
          "url": "paid-drama-sdk-1.0.3.aar",
          "size": 784045,
          "sha512": "a172577c69be2669325281d82f745062441fcbcc81fa1ba3071e51029090455aea29f2f7628d59152db036011123a84999bd40d36865237b9244b10fed8aaba2",
          "sha256": "3a104c87d590ac7998f23e4d1cc196ed91690fec98e7e27685f5d83bacb04931",
          "sha1": "0757cff1456a8657f5c7553a9e467ad1107da5af",
          "md5": "f72ddf0ff28c904fcacfe6f831888bc7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.3.aar",
          "url": "paid-drama-sdk-1.0.3.aar",
          "size": 784045,
          "sha512": "a172577c69be2669325281d82f745062441fcbcc81fa1ba3071e51029090455aea29f2f7628d59152db036011123a84999bd40d36865237b9244b10fed8aaba2",
          "sha256": "3a104c87d590ac7998f23e4d1cc196ed91690fec98e7e27685f5d83bacb04931",
          "sha1": "0757cff1456a8657f5c7553a9e467ad1107da5af",
          "md5": "f72ddf0ff28c904fcacfe6f831888bc7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.3-sources.jar",
          "url": "paid-drama-sdk-1.0.3-sources.jar",
          "size": 95571,
          "sha512": "9ac8bfc54d323b37a1b90d72649939d8aea827ab322bc28802dca7ac949f2167869609eaebf691a4a250298eb3512ec1fa3c618f85da7afbb1dd52cc53b68d7f",
          "sha256": "68e37caf91a89a4ff094e9225eefa3fcf29e6949571642df7acb35688c079322",
          "sha1": "ac3293c74486cfa24ebf06c027aa1c5b5e9f9123",
          "md5": "6f197fe274457868b0673708da0081a6"
        }
      ]
    }
  ]
}
