{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.aar",
          "url": "short-drama-sdk-1.0.aar",
          "size": 2492870,
          "sha512": "92956ce57e5253e7746737cf3ba4e27fd476fdf30fbb5f616452ed14b17272028033ce66513c98902b59af13122b865b2806ddf9ddf3512265456fa279a9fd03",
          "sha256": "3fe2af9dc80f72bf508087d517e9571d60474a0c79b33be9afba9270f845b81c",
          "sha1": "8c8dc8c9e640d3df40bf49769e6b8c7b67371cd7",
          "md5": "826698fa92e80d62113bdc32f66a3649"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.aar",
          "url": "short-drama-sdk-1.0.aar",
          "size": 2492870,
          "sha512": "92956ce57e5253e7746737cf3ba4e27fd476fdf30fbb5f616452ed14b17272028033ce66513c98902b59af13122b865b2806ddf9ddf3512265456fa279a9fd03",
          "sha256": "3fe2af9dc80f72bf508087d517e9571d60474a0c79b33be9afba9270f845b81c",
          "sha1": "8c8dc8c9e640d3df40bf49769e6b8c7b67371cd7",
          "md5": "826698fa92e80d62113bdc32f66a3649"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0-sources.jar",
          "url": "short-drama-sdk-1.0-sources.jar",
          "size": 99137,
          "sha512": "f46fe9907d809076c3abf53f91496fd7f96bcacbf6ccfb5e2930b67817dd9744caca5453695cdbb8bcb9118fab0670f893644e620d2ac0fec3cce74f0870565a",
          "sha256": "97174f4d0ac816ac9f9abe32bc3d44ee4077f70467fe4233c22dcf2a475ed8f6",
          "sha1": "6f058f82a4010945c3389273271e751b595f994a",
          "md5": "344cf634b8675601463429412cd60cac"
        }
      ]
    }
  ]
}
