{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.aar",
          "url": "short-drama-sdk-1.0.aar",
          "size": 14552435,
          "sha512": "42c1c9cc83b06c675e9d616c0c7663439fd9ffe3c901c7e6345b3dc708003a3aec497360cd6cc5570debe59a8892de8b8ea80417add0ba0377482cba534ad621",
          "sha256": "cb78a2d97165ee3de7b4186aa2187a2d41a988ac42eda09a6fc9d0c2af6590bc",
          "sha1": "781bbc43d1f1fd47379ca75c4126533a92b31a05",
          "md5": "6d58ea19408fd1ef9a3dcb0f61d04152"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.aar",
          "url": "short-drama-sdk-1.0.aar",
          "size": 14552435,
          "sha512": "42c1c9cc83b06c675e9d616c0c7663439fd9ffe3c901c7e6345b3dc708003a3aec497360cd6cc5570debe59a8892de8b8ea80417add0ba0377482cba534ad621",
          "sha256": "cb78a2d97165ee3de7b4186aa2187a2d41a988ac42eda09a6fc9d0c2af6590bc",
          "sha1": "781bbc43d1f1fd47379ca75c4126533a92b31a05",
          "md5": "6d58ea19408fd1ef9a3dcb0f61d04152"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0-sources.jar",
          "url": "short-drama-sdk-1.0-sources.jar",
          "size": 99519,
          "sha512": "73f48d68263604718641b0062d461030fca65a61285832f4eb60f0042a217bc9ddee0a69fe4af4a1047aac9a39a99f4e6bea7db7ef72a67a58ca243f43214433",
          "sha256": "e2c320281fd78cbfded7d6d736d3c9c80552aacae0535516b058268c75d81250",
          "sha1": "a3027ad3234a57fb870f20166edb0cb17036cb82",
          "md5": "44c2a5fca2a8e9ed528b3c4a529453c2"
        }
      ]
    }
  ]
}
