{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.aar",
          "url": "short-drama-sdk-1.0.aar",
          "size": 2490936,
          "sha512": "1193b0e486e30c79ce591af84ac70af1ae69af60d6fbda6c7938ebacccecb464d6b3e8221bf81fbd5f52e401e32d59f464fe7738ba85d506a288c5d7d265fe0c",
          "sha256": "66732f9e66f1df5c289219c8ea81a6d03ab8adfef1aa1d4dd5a32fc31eba2b23",
          "sha1": "c8c617830716ade40bb9cdd68426161249738796",
          "md5": "94c967cd91946568f918e7fa355b1c99"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.aar",
          "url": "short-drama-sdk-1.0.aar",
          "size": 2490936,
          "sha512": "1193b0e486e30c79ce591af84ac70af1ae69af60d6fbda6c7938ebacccecb464d6b3e8221bf81fbd5f52e401e32d59f464fe7738ba85d506a288c5d7d265fe0c",
          "sha256": "66732f9e66f1df5c289219c8ea81a6d03ab8adfef1aa1d4dd5a32fc31eba2b23",
          "sha1": "c8c617830716ade40bb9cdd68426161249738796",
          "md5": "94c967cd91946568f918e7fa355b1c99"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0-sources.jar",
          "url": "short-drama-sdk-1.0-sources.jar",
          "size": 98473,
          "sha512": "6705ae1401bffe7543ca649d27d1540f351d2f5811740394ae9faa3e3e6995d789aa7010aac2feca0d45df94e738a325b6f77e54658865589703d7c5d3144589",
          "sha256": "fe063aa3f0d9a66b7f135b9a616dd52708933ab6ac1266a73163b8fe627f6b11",
          "sha1": "5f1ee23224c9f89a6d22ba0202fb468a8b1025ef",
          "md5": "1858970a9c694669d0c4b90585a8f26c"
        }
      ]
    }
  ]
}
