{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.5.aar",
          "url": "paid-drama-sdk-1.0.5.aar",
          "size": 791102,
          "sha512": "eb9093e5b201b624af7bb28f9ade117237e1510060cdb24b38911c58a36254a6aff4c0873b82a85546ec1a235a6ec0dc08ee970863df52d6dd1eef52f69ab54c",
          "sha256": "183a07589cba9126c620df7db16a05b3295f182f68254effe4700d529a6c5f1a",
          "sha1": "f070873a7d5a6442b0d259c3bf2f4db85e81a5ef",
          "md5": "a2e7b65ba840166ae6ac534ed5e08c2b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.5.aar",
          "url": "paid-drama-sdk-1.0.5.aar",
          "size": 791102,
          "sha512": "eb9093e5b201b624af7bb28f9ade117237e1510060cdb24b38911c58a36254a6aff4c0873b82a85546ec1a235a6ec0dc08ee970863df52d6dd1eef52f69ab54c",
          "sha256": "183a07589cba9126c620df7db16a05b3295f182f68254effe4700d529a6c5f1a",
          "sha1": "f070873a7d5a6442b0d259c3bf2f4db85e81a5ef",
          "md5": "a2e7b65ba840166ae6ac534ed5e08c2b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.5-sources.jar",
          "url": "paid-drama-sdk-1.0.5-sources.jar",
          "size": 95987,
          "sha512": "ab411b1810c40b69e84d1eefde8ff172d9f47f8ce2a635376f1783baf5c251e9f7ef67d5d1a8ed9b042adab94c7535f2acaf81e50286d6378526b0067f5fc30a",
          "sha256": "e61b68b158ec238d7a436b2765893d5e03a634f247343090a753bcd9b241615e",
          "sha1": "88d0bb9d3d948b1aaf10a6e7c5be4392cd7c1bd8",
          "md5": "d1e6d41c54e6d60d04aadd7f07965037"
        }
      ]
    }
  ]
}
