{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7.5"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.5.aar",
          "url": "paid-drama-sdk-1.0.5.aar",
          "size": 790892,
          "sha512": "033cb9835d4b9c422db20ce2baf96edde01b9f1e40d6daacc77e5586ddeff1d26117b4d83cb21de9d85171ef7a17212c890804d2cf3eb59dbdb561e47b94aad6",
          "sha256": "f3a14b21433c00d51c9f7748f7ddd134a12bb594aa035aa101e01480d1fc1b3b",
          "sha1": "3c43e8ee8835815d9e2c6eb019122ab45c60720d",
          "md5": "6547765de604e6276a77e3987e3ffc91"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7.5"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.5.aar",
          "url": "paid-drama-sdk-1.0.5.aar",
          "size": 790892,
          "sha512": "033cb9835d4b9c422db20ce2baf96edde01b9f1e40d6daacc77e5586ddeff1d26117b4d83cb21de9d85171ef7a17212c890804d2cf3eb59dbdb561e47b94aad6",
          "sha256": "f3a14b21433c00d51c9f7748f7ddd134a12bb594aa035aa101e01480d1fc1b3b",
          "sha1": "3c43e8ee8835815d9e2c6eb019122ab45c60720d",
          "md5": "6547765de604e6276a77e3987e3ffc91"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.5-sources.jar",
          "url": "paid-drama-sdk-1.0.5-sources.jar",
          "size": 96061,
          "sha512": "8518ce9537a9a6eba1ec2311763531ea882d711410bc5b3a7dcb175e2a56ed630fefb6830124fce7e131425e89aab035c5186a73cea2e81ed85485a0b0688316",
          "sha256": "6c23f33c3ea51c0a74dc7c22f49b1ac337405c83245ed62111ec636224f16155",
          "sha1": "8df10e831fbf306e7b67711369f0976b3081337c",
          "md5": "e4457235ee776534ae308b4f533d4923"
        }
      ]
    }
  ]
}
