{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.6.1.aar",
          "url": "paid-drama-sdk-1.0.6.1.aar",
          "size": 792177,
          "sha512": "63ea6cfac8702ea3fa8e3cb95b019560667d8d426a849f577ba2d1f9cfae4d7395a76480814f4e437eccf194458ecf6c56cfc407b780234c6a4143beb0cc836f",
          "sha256": "f87e741643ab645a8ba90d6e5bfba4523541079da0168544fd68fd47dd1a3beb",
          "sha1": "e55b87cf03932ca127046fdb79258f7aef901f2e",
          "md5": "7cf9b90f0e40d636268e451e4c6910e2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.6.1.aar",
          "url": "paid-drama-sdk-1.0.6.1.aar",
          "size": 792177,
          "sha512": "63ea6cfac8702ea3fa8e3cb95b019560667d8d426a849f577ba2d1f9cfae4d7395a76480814f4e437eccf194458ecf6c56cfc407b780234c6a4143beb0cc836f",
          "sha256": "f87e741643ab645a8ba90d6e5bfba4523541079da0168544fd68fd47dd1a3beb",
          "sha1": "e55b87cf03932ca127046fdb79258f7aef901f2e",
          "md5": "7cf9b90f0e40d636268e451e4c6910e2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.6.1-sources.jar",
          "url": "paid-drama-sdk-1.0.6.1-sources.jar",
          "size": 96813,
          "sha512": "4bc8036dd31cd06e58ce6e5e3833dad1a7b78013e0d7849ea3ab94844d73e1b06bf4446ae4f7fa8445807de20b7b239f0cc158b16e6abcf04f665e6bc0135d0c",
          "sha256": "406fe4d4399c1a11541821f0bed7d4eb802acb6d3b8f08e4ad9ce9bebc0e40ff",
          "sha1": "5c8a84e5faacdbfe2a6630013869804977ac5302",
          "md5": "044996b11bd058a02021cd62167d651b"
        }
      ]
    }
  ]
}
