{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.5.aar",
          "url": "short-drama-sdk-1.0.5.aar",
          "size": 2546624,
          "sha512": "77ba4dd99ea034cc5124cb7b68610d72bf0692e24d1eefd0e5ecb269c13d28c44b71e80769a2e2150adfb7e503e4027e60452af974c89c2ab923429fdeb198e9",
          "sha256": "e52cfb97db0739434462e6d20133d3da850aa5a06b0492c6603847bb2b0234fc",
          "sha1": "638310b8ff9413cb97b36b39b0f505579de50266",
          "md5": "a7b2edd2e2715e7c83801825cebb0117"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.5.aar",
          "url": "short-drama-sdk-1.0.5.aar",
          "size": 2546624,
          "sha512": "77ba4dd99ea034cc5124cb7b68610d72bf0692e24d1eefd0e5ecb269c13d28c44b71e80769a2e2150adfb7e503e4027e60452af974c89c2ab923429fdeb198e9",
          "sha256": "e52cfb97db0739434462e6d20133d3da850aa5a06b0492c6603847bb2b0234fc",
          "sha1": "638310b8ff9413cb97b36b39b0f505579de50266",
          "md5": "a7b2edd2e2715e7c83801825cebb0117"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0.5-sources.jar",
          "url": "short-drama-sdk-1.0.5-sources.jar",
          "size": 122549,
          "sha512": "bdab90f2f1a202c3be402489ac579beedd0308f9fad44caf1f7037cb32c1f821a386218d9d5c46f0a36180f14bfff51408352f698e1a5a64d89fad39c4bfa725",
          "sha256": "ffd97d308fc15c3ebe6f9c8cf6fad489165826f8ecf25705556de59d4a921b0a",
          "sha1": "eb6f13edc624e8b5fd1580dd9e9af833a9724f4f",
          "md5": "3184e4c49e864e1da06b8866fcfc0a9d"
        }
      ]
    }
  ]
}
