{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.8"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.2.aar",
          "url": "short-drama-sdk-1.0.2.aar",
          "size": 2485161,
          "sha512": "d7606673ba21cc972917746c1cdf680c4bcc4e16aaad7e183dd0c4827c448e7109da392cf995f08545df2c82cdc0046ae7898f1e4586422734fb1bc7cc52e1f5",
          "sha256": "0165a1507c12a2bda60349b84a6aec20bc7a0fd19911c93a2da6e66dc3a84a7f",
          "sha1": "304756aa4bdeb008c39c64ed40b6d94c989f199f",
          "md5": "eb61ce9ba5f0278c13585abef18822f5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.8"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.2.aar",
          "url": "short-drama-sdk-1.0.2.aar",
          "size": 2485161,
          "sha512": "d7606673ba21cc972917746c1cdf680c4bcc4e16aaad7e183dd0c4827c448e7109da392cf995f08545df2c82cdc0046ae7898f1e4586422734fb1bc7cc52e1f5",
          "sha256": "0165a1507c12a2bda60349b84a6aec20bc7a0fd19911c93a2da6e66dc3a84a7f",
          "sha1": "304756aa4bdeb008c39c64ed40b6d94c989f199f",
          "md5": "eb61ce9ba5f0278c13585abef18822f5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0.2-sources.jar",
          "url": "short-drama-sdk-1.0.2-sources.jar",
          "size": 95413,
          "sha512": "dcd1680a1f6f981ed2ac8632b8783066c5602000ab6f2ab141087927848c079caa4360f8f98d0047e05c17e0d298a69dd65a0c1ff82bd0e29fd6f430ad498413",
          "sha256": "62f89f37cb771ee27d8016645fa2f0d099ff300c7658824fe8ad55bf6f7ebd0e",
          "sha1": "672ea50615aab44859f7473110ea05c5aa356034",
          "md5": "c7f37d05e57d3df9694165337c68eac9"
        }
      ]
    }
  ]
}
