{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.2"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-media3",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ui",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2.aar",
          "url": "paid-drama-sdk-1.0.2.aar",
          "size": 794217,
          "sha512": "87c7e8effc47b7388b005152aa12c5913ccfec4657dc817f85112d70fd4a5d169e94a503d7d6e45bd71131db77c0d2a00b08978f77be40514995e5e2f47ef768",
          "sha256": "6dc79058b2daa468cc71661787f15a02cd47818e0e86b5a8852d3581a21e1d4b",
          "sha1": "f3528d7a87d3055ba1070fe922dae6441ebc387b",
          "md5": "1d8c7f4e294e0f0036ada072a8cc2e8b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.2"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-media3",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ui",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2.aar",
          "url": "paid-drama-sdk-1.0.2.aar",
          "size": 794217,
          "sha512": "87c7e8effc47b7388b005152aa12c5913ccfec4657dc817f85112d70fd4a5d169e94a503d7d6e45bd71131db77c0d2a00b08978f77be40514995e5e2f47ef768",
          "sha256": "6dc79058b2daa468cc71661787f15a02cd47818e0e86b5a8852d3581a21e1d4b",
          "sha1": "f3528d7a87d3055ba1070fe922dae6441ebc387b",
          "md5": "1d8c7f4e294e0f0036ada072a8cc2e8b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2-sources.jar",
          "url": "paid-drama-sdk-1.0.2-sources.jar",
          "size": 107979,
          "sha512": "42ee874fea7af62a2f0208fcf85a90f7db11846d78f7d33d6dd0aa69fa71c3414a049ecb7f7d1e15abec75f7f6751059d5fec45f6974886401fec20dde390861",
          "sha256": "915e03773189dbd1e46d83860c5513718d0e9e07d270f7d90eab325330875f88",
          "sha1": "45a7d78379d84f05e0a470ac08f2ac8d7e732fac",
          "md5": "b021f71981dd0cc551e487f88bf1b4fe"
        }
      ]
    }
  ]
}
