{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.2"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-media3",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ui",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2.aar",
          "url": "paid-drama-sdk-1.0.2.aar",
          "size": 794380,
          "sha512": "599793ebfa8cb014b97c2d97b36ea28bc14b8a6e32c0f14130c0eec586df3b053b382d2894709bc4df308634f4d6986bee6ff94a027b3ba5b52c6dbf952e6ad9",
          "sha256": "a783f6dec612e52ed9d240d0a6b29ec99e547e3cfe21ddca6d5302717927cda0",
          "sha1": "b4142020d777ac43f3f1c8a70dcf51a5442e8b7d",
          "md5": "02bcad837d2f11aba038967b68392348"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.2"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-media3",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ui",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2.aar",
          "url": "paid-drama-sdk-1.0.2.aar",
          "size": 794380,
          "sha512": "599793ebfa8cb014b97c2d97b36ea28bc14b8a6e32c0f14130c0eec586df3b053b382d2894709bc4df308634f4d6986bee6ff94a027b3ba5b52c6dbf952e6ad9",
          "sha256": "a783f6dec612e52ed9d240d0a6b29ec99e547e3cfe21ddca6d5302717927cda0",
          "sha1": "b4142020d777ac43f3f1c8a70dcf51a5442e8b7d",
          "md5": "02bcad837d2f11aba038967b68392348"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2-sources.jar",
          "url": "paid-drama-sdk-1.0.2-sources.jar",
          "size": 107989,
          "sha512": "35c63087377126956c713e0bf3f1d98c9ceb407b39bad6c9105e7dd9abab58fafddfc06c234cc5c8b1883cca258cd4a522a421c5083e185f7140db854a34fe14",
          "sha256": "eff42cb4d79b69783f7d688966490a523f1a4300d6280e99a408a88e09fa4bd6",
          "sha1": "098fc48cf4d459980a12e7875f65e299256b6b4c",
          "md5": "54ad3046a93cad39237a5d42143164fc"
        }
      ]
    }
  ]
}
