{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.3"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-media3",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ui",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2.aar",
          "url": "paid-drama-sdk-1.0.2.aar",
          "size": 794638,
          "sha512": "8664a0cfae47fcd47ea79436f23a529d41abcc713c40f3294007619ec84560f019e8ab9a136c0f802eea7e56fd1a0ef11f449ee60d275e5453fff9bc9a1d1ef4",
          "sha256": "4a2726adc60691b99b661306f02d549f8352800ac56bf563a61eb29078e6bfbe",
          "sha1": "7ca1d7be3eb0584e2f024a0569aa9ca29740a165",
          "md5": "3a1572c25256fa1b67300a902277d737"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2.3"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-media3",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ui",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2.aar",
          "url": "paid-drama-sdk-1.0.2.aar",
          "size": 794638,
          "sha512": "8664a0cfae47fcd47ea79436f23a529d41abcc713c40f3294007619ec84560f019e8ab9a136c0f802eea7e56fd1a0ef11f449ee60d275e5453fff9bc9a1d1ef4",
          "sha256": "4a2726adc60691b99b661306f02d549f8352800ac56bf563a61eb29078e6bfbe",
          "sha1": "7ca1d7be3eb0584e2f024a0569aa9ca29740a165",
          "md5": "3a1572c25256fa1b67300a902277d737"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0.2-sources.jar",
          "url": "paid-drama-sdk-1.0.2-sources.jar",
          "size": 108199,
          "sha512": "bd0632f2134d3f304acd714615921b56343bf2ea5bbc96f58562082f7e35e2903d36626d1958afe6d7ccbaf4f4ff4fee68a6c48d96b295d8cd49c016bf7b3a10",
          "sha256": "8a693e02bf908f63730baaa9f9a804e08864435f7f929ed5146ae3e20b81ffba",
          "sha1": "fcb97170286f2edd45eb683fabf0e4d4a5b2511d",
          "md5": "77fbfafe553ea7091bbd3f1a59401aea"
        }
      ]
    }
  ]
}
