{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.4.aar",
          "url": "short-drama-sdk-1.0.4.aar",
          "size": 2545117,
          "sha512": "4131c74bfcef4968015e5aa34ea44f2d6de55fb82557136545127c44cafb5322a79c01d2804786771bc446f932ecd6800a4a153e4fe81f32cb6c1ab54903ebc6",
          "sha256": "e82310f19342fa911066df8759b955eba0ce49c81fe49c94a1702a147d278343",
          "sha1": "4828ede3e28849d3df7067179a3f81e6d3701f6b",
          "md5": "42441466b207285785d7033944458b88"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.4.aar",
          "url": "short-drama-sdk-1.0.4.aar",
          "size": 2545117,
          "sha512": "4131c74bfcef4968015e5aa34ea44f2d6de55fb82557136545127c44cafb5322a79c01d2804786771bc446f932ecd6800a4a153e4fe81f32cb6c1ab54903ebc6",
          "sha256": "e82310f19342fa911066df8759b955eba0ce49c81fe49c94a1702a147d278343",
          "sha1": "4828ede3e28849d3df7067179a3f81e6d3701f6b",
          "md5": "42441466b207285785d7033944458b88"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0.4-sources.jar",
          "url": "short-drama-sdk-1.0.4-sources.jar",
          "size": 121899,
          "sha512": "52a0804637c986540679da7d8311f43a2ecd395e030ede0584aaf719aa84292f088f75495e10e9fd05ebd3bc617fa747b228589183680beb93d1783a26151b61",
          "sha256": "3fe758b04f724a02c5a4e4a12b0b95aba4232e648066f0836e281a103d6c5852",
          "sha1": "380111867319813d2dacd2f31757278bddb238a1",
          "md5": "58ad0de6d8a9b62ca78e20c7deb310ee"
        }
      ]
    }
  ]
}
