{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.8"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.4.aar",
          "url": "short-drama-sdk-1.0.4.aar",
          "size": 2545785,
          "sha512": "b2a3e5dc1c0bab11b8d83d4625006a477c34dd9e0715465cf370dbecfb086c241a99a0365aecc7a510b63c4b774faf7fccc56ee076bed697bac6062c8c5f593f",
          "sha256": "8de95b8c379b21568e018726b1d48822c86957277ae32384379d8cd82b93569f",
          "sha1": "295fc1d7d1f7b14997740ba467c3d429e1668006",
          "md5": "84d39c9d8bc4d9e9f978e38e38520e6a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.8"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.4.aar",
          "url": "short-drama-sdk-1.0.4.aar",
          "size": 2545785,
          "sha512": "b2a3e5dc1c0bab11b8d83d4625006a477c34dd9e0715465cf370dbecfb086c241a99a0365aecc7a510b63c4b774faf7fccc56ee076bed697bac6062c8c5f593f",
          "sha256": "8de95b8c379b21568e018726b1d48822c86957277ae32384379d8cd82b93569f",
          "sha1": "295fc1d7d1f7b14997740ba467c3d429e1668006",
          "md5": "84d39c9d8bc4d9e9f978e38e38520e6a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0.4-sources.jar",
          "url": "short-drama-sdk-1.0.4-sources.jar",
          "size": 122001,
          "sha512": "38247fd09acf221cdb57c0ecf208065e53690ab378dd337a3fcb14d4352d1f328d9531258a77b08297bc49a75c15dc0acb2a85ec177f7bcd63fb41bf2f8759df",
          "sha256": "23b4edba88bd60a880cd79274bed7ae7e53e94b40b545daeece49ec340b8324a",
          "sha1": "2cdfa6c3dbd0922f2d59e2f01303457c84f7614b",
          "md5": "c2df4da808b830e6406c79bc324956c2"
        }
      ]
    }
  ]
}
