{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "short-drama-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.8"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.4.aar",
          "url": "short-drama-sdk-1.0.4.aar",
          "size": 2545794,
          "sha512": "a2bead805c587c4ce5842ce0035b2dd707ecab9e91a5b03ab149858926c182889150c8844002bb9a429623e65872723d4c536b3223dfb3f64ba89e5f26bf826b",
          "sha256": "ccc8c95feeb7d16c3a73335d4e25f6e95673a2e460f8894baf38e286a52d0ceb",
          "sha1": "bca01d8cc4ac9b55a3f93241d9ab8b81b5990a44",
          "md5": "b3172450e7bc69a841d8ceba1ece92cd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.2.8"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "short-drama-common",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.cymchad",
          "module": "BaseRecyclerViewAdapterHelper4",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "short-drama-sdk-1.0.4.aar",
          "url": "short-drama-sdk-1.0.4.aar",
          "size": 2545794,
          "sha512": "a2bead805c587c4ce5842ce0035b2dd707ecab9e91a5b03ab149858926c182889150c8844002bb9a429623e65872723d4c536b3223dfb3f64ba89e5f26bf826b",
          "sha256": "ccc8c95feeb7d16c3a73335d4e25f6e95673a2e460f8894baf38e286a52d0ceb",
          "sha1": "bca01d8cc4ac9b55a3f93241d9ab8b81b5990a44",
          "md5": "b3172450e7bc69a841d8ceba1ece92cd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "short-drama-sdk-1.0.4-sources.jar",
          "url": "short-drama-sdk-1.0.4-sources.jar",
          "size": 122033,
          "sha512": "6bce91376901c98a20df7063950d8d978e1aca021deea738423d1eb7a2f32cca0679ae50aeb71a21f4a4ed6c70322563a20eafe5eeeeec1ca4f36b14e1c53ec5",
          "sha256": "8fd1d427ee3870e51d34c06b6b5df4d1666f9bcc1305c83fba678613dc58b290",
          "sha1": "5a3e5082e76f611d2b9cc56b253a166578bb1dbb",
          "md5": "f4cdb69c4c868842d296712222c94630"
        }
      ]
    }
  ]
}
