{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "paid-drama-sdk",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-java",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-ui",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "player-ijk",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.aar",
          "url": "paid-drama-sdk-1.0.aar",
          "size": 758758,
          "sha512": "b820aac01e4753a12bf062bbde38bd6bbc6df5072937a6fad6c5a9e173ad323c2d89b3cd1b65294675b6dfce6e450f7d38fee37cb4bbefd6bee017017d3051b8",
          "sha256": "7050034e8bc8d77944d34f5c44703d4b7dc3b93726932f5a90d909f2b5791336",
          "sha1": "74cc4304f39d3b96e54d192d396ad9086b28527e",
          "md5": "cfbc869ca406f41030ba55f9fa36490a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-java",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-ui",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "seattle_tv_sdk",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "player-ijk",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "paid-drama-sdk-1.0.aar",
          "url": "paid-drama-sdk-1.0.aar",
          "size": 758758,
          "sha512": "b820aac01e4753a12bf062bbde38bd6bbc6df5072937a6fad6c5a9e173ad323c2d89b3cd1b65294675b6dfce6e450f7d38fee37cb4bbefd6bee017017d3051b8",
          "sha256": "7050034e8bc8d77944d34f5c44703d4b7dc3b93726932f5a90d909f2b5791336",
          "sha1": "74cc4304f39d3b96e54d192d396ad9086b28527e",
          "md5": "cfbc869ca406f41030ba55f9fa36490a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paid-drama-sdk-1.0-sources.jar",
          "url": "paid-drama-sdk-1.0-sources.jar",
          "size": 96529,
          "sha512": "feb27ed4798cc84b46d67dcb494fa00e95ad66eb95e9e8af864159f27e87452ea1947cd957192c254fe1727027aa21598913eead27588c7fd81d040fbe582ffe",
          "sha256": "7e000b8b417c72094d2ae48203f66db16221a52e3d1d5591abd09e05a54c5c41",
          "sha1": "ea461bfc8ec804dc30cf18ae88bafa68e6d5d62d",
          "md5": "f865dbbad50fc488b1fd083666325c70"
        }
      ]
    }
  ]
}
